name: test262

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test262:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Sync submodules
        run: git submodule update --init --recursive
      - name: Install MoonBit
        shell: bash
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s "latest"
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: Moon update
        run: moon update
      - name: Apply test262 patch
        run: |
          if git -C test262 apply --check ../test262-config/test262.patch; then
            git -C test262 apply ../test262-config/test262.patch
          fi
      - name: Verify test262 checkout
        run: test -d test262/test
      - name: Run test262
        run: |
          moon run --target native --release cmd/test262 -- -c test262-config/test262.conf
